channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - numpy==2.3.3
  - packaging==25.0
  - pandas==2.3.3
  - psutil==7.1.2
  - pyarrow==21.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.7.2
  - scipy==1.16.2
  - xgboost==3.0.1
name: mlflow-env
